### ISSUE TITLE
Finding Chromecasts

### ISSUE THREAD

**Issue by janarthenan** [yuzawa-san/googolplex-theater#21]
The application is unable to find any of my devices?
In the code - I have specified the name of the chromecast device.
Multicast is enabled on router, Java installed, Google chrome is able to find and cast to the device.

**Comment by yuzawa-san** [comment]
Let's continue using this issue until we figure out what is going on.

It is possible that the googolplex-theater application is not looking for the chromecasts correctly. Please post first several dozen lines of the application log output. There is some information in there that may be of use. Specifically the network interface being used for multicast device discovery. There is a line with "Search for casts using" of particular interest. Please provide the output of the command `ifconfig` or another network tool which lists your available network interfaces.

Is anything showing up in the web UI? What OS are you using? What version of Java are you using?

**Comment by janarthenan** [comment]
`Microsoft Windows [Version 10.0.19041.388]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\Admin>cd C:\GoogolPlex\bin

C:\GoogolPlex\bin>googolplex-theater
15:11:25.871 [main] INFO  com.jyuzawa.googolplex_theater.GoogolplexTheater - Starting up Googolplex Theater!
15:11:25.882 [main] INFO  com.jyuzawa.googolplex_theater.GoogolplexTheater - Website: https://github.com/yuzawa-san/googolplex-theater
15:11:29.588 [main] INFO  com.jyuzawa.googolplex_theater.client.GoogolplexControllerImpl - Using cast application id: B1A3B99B
15:11:29.703 [main] INFO  com.jyuzawa.googolplex_theater.config.CastConfigLoader - Using cast config: C:\GoogolPlex\bin\src\dist\conf\cast_config.json
15:11:29.709 [main] INFO  com.jyuzawa.googolplex_theater.config.CastConfigLoader - Reloading cast config
15:11:31.114 [vert.x-eventloop-thread-1] INFO  com.jyuzawa.googolplex_theater.client.GoogolplexControllerImpl - CONFIG_UPDATED 'Family room TV'
Oct 23, 2020 3:11:32 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main]=Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2624 ms, time limit is 2000 ms
Oct 23, 2020 3:11:33 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main]=Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3863 ms, time limit is 2000 ms
15:11:33.806 [main] INFO  com.jyuzawa.googolplex_theater.mdns.ServiceDiscovery - Search for casts using DESKTOP-G21GO6O/192.168.0.71
Oct 23, 2020 3:11:34 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main]=Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4878 ms, time limit is 2000 ms
15:11:34.800 [vert.x-eventloop-thread-0] INFO  com.jyuzawa.googolplex_theater.server.GoogolplexServer - Running web-ui server on port 8000
`
Java 8.x, Windows 10

`Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . :
   IPv6 Address. . . . . . . . . . . : 2a02:2f0e:510:b100:bccb:3134:4353:6df
   Temporary IPv6 Address. . . . . . : 2a02:2f0e:510:b100:5d44:f1d8:875c:a916
   Link-local IPv6 Address . . . . . : fe80::bccb:3134:4353:6df%9
   IPv4 Address. . . . . . . . . . . : 192.168.100.13
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : fe80::1%9
                                       192.168.100.1

Wireless LAN adapter WiFi:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Local Area Connection* 1:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Ethernet adapter Bluetooth Network Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :`

**Comment by yuzawa-san** [comment]
Thank you for sending this. It is quite helpful. I noticed a few things:
* You are on windows. Sadly I have not tested on this OS, since I do not have access to any computers for testing. It is unclear whether this is a Window-specific issue.
* There seems to be a mismatch between the `Search for casts using DESKTOP-G21GO6O/192.168.0.71` and the `IPv4 Address. . . . . . . . . . . : 192.168.100.13` in the interface list. Are you connected to wifi or a vpn sometimes? A short term solution would be to specify the interface name in the command line arguments.

I'm not fully sold on the logic our multicast library JmDNS uses to select an interface, so I may reconsider the default behavior there. I may also add some hints or candidate interface names to make this easier.

**Comment by janarthenan** [comment]
Hi
I located the issue - it was the laptop while on wifi would not find the devices. Once I connected via the wired connection - found all devices on the network.
J

**Comment by yuzawa-san** [comment]
OK thanks for the update. Is everything working properly now? I advise you use the ethernet for stability. You are free to use the application however you want, but I cannot guarantee the automatic reconnection logic will function correctly in cases where the laptop is on wireless internet (possibly roaming) or if the laptop is closed or put to sleep. In the latter case, the Chromecasts may disconnect. It is too hard to build to support those use cases.

**Comment by yuzawa-san** [comment]
I have updated the documentation https://github.com/yuzawa-san/googolplex-theater#troubleshooting and also made some changes related to how the network interfaces are detected. I no longer depend fully on the JmDNS to auto-detect. The application log output is also more clear about what network interfaces are available. Feel free to download master and give it a try and let me know if anything odd is happening. Once I get back to my chromecasts to do some more testing, I'll add those to the next release.
