### ISSUE TITLE
Continuous connection

### ISSUE THREAD

**Issue by janarthenan** [yuzawa-san/googolplex-theater#26]
**Is your feature request related to a problem? Please describe.**
Currently if the command prompt is closed, all chromecasts revert back to default view and your display is closed until you rerun googolplex.

**Describe the solution you'd like**
Once a connection is made and the link sent - it should continue casting until the cast is interrupted.
See https://boombatower.github.io/chromecast-dashboard/sender/
the link stays live even after the browser is closed?

**Describe alternatives you've considered**
run as service and autostartup - but if pc is off - cast is off

**Comment by yuzawa-san** [comment]
This application is not built to work after it is shut down. To elaborate on https://github.com/yuzawa-san/googolplex-theater/issues/21#issuecomment-716236568 I would advise against running the application on a laptop (which may be open and closed periodically or put to sleep) and use a dedicated piece of hardware (like a desktop computer with sleep disabled, or a Raspberry Pi) which can be continuously be up and running. I cannot guarantee the behavior of recovering after coming out of sleep beyond that it should attempt to try to reconnect.

Could you elaborate on your use case?

**Comment by janarthenan** [comment]
The application is currently running on a PC - which is in use by other users, who unfortunately switch the device at the end of shift. so losing all the cast when this happens. I have now invested in a raspberry Pi and am setting it up.
One issue I do find is - the Chromecasts are on GuestWiFi and a seperate VLAN - as the application can only select one interface this makes it difficult on a raspberry pi as all the VLANS have to setup as seperate interfaces.
So my test bench which is on the corporate WiFi and a different VLAN to the GuestWiFi is not being picked up.
